pipeline:
  install:
    image: node:${NODE_VERSION}
    commands:
      - npm install

  lint:
    image: node:${NODE_VERSION}
    commands:
      - npm run lint

  test:
    image: node:${NODE_VERSION}
    environment:
      - MONGO_HOST=localhost
    commands:
      - npm run test

  docker:
    image: registry.monstrs.net:5000/drone-docker
    privileged: true
    registry: registry.monstrs.net:5000
    repo: registry.monstrs.net:5000/api
    tag: [ "latest" ]
    environment:
      - DOCKER_LAUNCH_DEBUG=true

  ssh:
    image: registry.monstrs.net:5000/drone-ssh
    host: 193.124.177.25
    timeout: 30
    commands:
      - systemctl restart avrs-api

services:
  mongo:
    image: mongo
    pull: true

matrix:
  NODE_VERSION:
    - 6
