pipeline:
  install:
    image: node:${NODE_VERSION}
    commands:
      - apt-get update
      - apt-get -y install libmcrypt-dev
      - npm install

  lint:
    image: node:${NODE_VERSION}
    commands:
      - npm run lint

  test:
    image: node:${NODE_VERSION}
    environment:
      - DB_HOST=localhost
      - REDIS_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    commands:
      - npm run db:drop
      - npm run db:create
      - npm run db:migrate
      - npm run test

  docker:
    image: registry.monstrs.net:5000/drone-docker
    privileged: true
    registry: registry.monstrs.net:5000
    repo: registry.monstrs.net:5000/api
    tag: [ "latest" ]
    environment:
      - DOCKER_LAUNCH_DEBUG=true

  ssh:
    image: registry.monstrs.net:5000/drone-ssh
    host: 193.124.177.25
    timeout: 30
    commands:
      - systemctl restart avrs-api

services:
  postgres:
    image: postgres
    pull: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    pull: true

matrix:
  NODE_VERSION:
    - 7
