version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8499:80"

  npm:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm

  mongo:
    image: mongo

  dev:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  test:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run test
    environment:
      - MONGO_DB=avrs-test
    depends_on:
      - mongo

  server:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongo
