version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8499:80"

  install:
    image: node
    volumes:
      - ./:/workspace
    entrypoint: bash -c "apt-get update && apt-get -y install libmcrypt-dev && cd /workspace && npm install"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  redis:
    image: redis

  npm:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
    entrypoint: npm
    depends_on:
      - postgres

  sequelize:
    image: node
    working_dir: /workspace
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - ./:/workspace
    entrypoint: ./node_modules/.bin/sequelize

  mailer:
    image: avrs-mailer
    depends_on:
      - redis

  dev:
    image: node
    working_dir: /workspace
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - NODE_ENV=development
    volumes:
      - ./:/workspace
    entrypoint: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - mailer

  test:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run test
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=avrs_test
    depends_on:
      - postgres
      - redis

  server:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
